servers:
  - port: 25587
    directory: D:\Minecraft\hub-server
    binary: paper-1.20.4-416.jar
    memory: 512
    maxPlayers: 5
    online: false
    detached: true
  - port: 25592
    directory: D:\Minecraft\survival-server
    binary: paper-1.20.4-416.jar
    memory: 4096
    maxPlayers: 5
    online: false
    detached: true
  - port: 25593
    directory: D:\Minecraft\squirrel
    binary: paper-1.20.4-416.jar
    memory: 4096
    maxPlayers: 5
    online: false
    detached: true
  - port: 25595
    directory: D:\Minecraft\breezecraft
    binary: paper-1.20.4-416.jar
    memory: 4096
    maxPlayers: 5
    online: false
    detached: true
  - port: 25596
    directory: D:\Minecraft\seth-mimi-luke-clarissa
    binary: paper-1.20.4-416.jar
    memory: 4096
    maxPlayers: 5
    online: false
    detached: true
  - port: 25597
    directory: D:\Minecraft\cedar-server
    binary: paper-1.20.4-416.jar
    memory: 2048
    maxPlayers: 5
    online: false
    detached: true
  - port: 25598
    directory: D:\Minecraft\creative-server
    binary: paper-1.20.4-416.jar
    memory: 1024
    maxPlayers: 5
    online: false
    detached: true

bungee:
  directory: D:\Minecraft\bungeecord-server
  binary: BungeeCord.jar
  memory: 512
